In [7]:
import pandas as pd
import json
import ast

In [2]:
df = pd.read_csv('ZonasMilitares/ZONAS_Y_DISTRITOS_MILITARES_EJERCITO_NACIONAL.csv')
df

,ZONA,ZONA -DIM,DIRECCION,CIUDAD,TELEFONO,LOCATION
0,1,Zona 01,Cl 25 Cra 1 barrio el Dorado,Tunja,(601) - 3208327124,"(5.53598, -73.34987)"
1,1,6,Cl 7 Nº 6-05 Barrio ricaurte,Chiquinquira,(601) - 3208328458,"(5.60998, -73.82092)"
2,1,7,Carrera 11bN°140a-64,Tunja,(601) - 3203912367,"(5.53598, -73.34987)"
3,1,8,Cra 11 30-00 KM4 VIA IZA,SOGAMOSO,(601) - 3203912368,"(5.67953, -72.95654)"
4,1,49,Cra 9 N° 5 Impar Barrio El Gaitán Barbosa - Sa...,Barbosa,(601) - 3208328461,"(5.92906, -73.61982)"
...,...,...,...,...,...,...
67,15,Zona 15,Carrera 11bN°104a-64,BOGOTA,(601) - 3208327130,"(4.7109886, -74.072092)"
68,15,1,Carrera 11bN°104a-64,BOGOTA,(601) - 3203911145,"(4.7109886, -74.072092)"
69,15,2,Calle19 sur N°6- 40,BOGOTA,(601) - 3203911150,"(4.7109886, -74.072092)"
70,15,3,Calle 33 sur N°79-80,BOGOTA,(601) - 3203911153,"(4.7109886, -74.072092)"
71,15,4,Carrera 11bN°104a-64,BOGOTA,(601) - 3203911154,"(4.7109886, -74.072092)"

In [10]:
datajson = []
c = df["LOCATION"].apply(ast.literal_eval)

for i in range(0,len(df)):
            
    coords = {'lat': c[i][0], 'lng': c[i][1]}
    datajson.append(coords)

In [11]:
save_file3 = open("zonasMilitares.json", "w") 
json.dump(datajson, save_file3, indent = 6) 
save_file3.close()